version: "3.8"

services: 
  nginx:
    restart: always
    container_name: ui_nginx
    network_mode: host
    build:
      dockerfile: ${PROJECT_ROOT}/setup/setup/ui/Dockerfile
      context: ${UI_PROJECT_PATH}
    volumes:
      - ${PROJECT_ROOT}/setup/certificates:/certificates
      - ${PROJECT_ROOT}/setup/setup/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
