version: '3.8'



networks:
  vs-net:
    external: true

services:
  videoserver:
    restart: always
    build:
      dockerfile: ${PROJECT_ROOT}/setup/setup/video-server/Dockerfile
      context: ${PROJECT_ROOT}
    image: iudx_vs/backend-server
    container_name: videoserver
    networks: 
      - vs-net
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    command: "npm start"


