version: "3.8"

volumes:
    pg_data:
    pgadmin:

services:
    postgres:
        image: postgres
        container_name: pg_container
        restart: always
        logging:
            options:
                max-size: 10m
                max-file: "10"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_INITDB_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_INITDB_PASSWORD}
            POSTGRES_DB: ${POSTGRES_INITDB_DATABASE}
        volumes:
            - ${SCHEMA_FILE}:/docker-entrypoint-initdb.d/schema.sql
            - pg_data:/var/lib/postgresql/data/

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin_container
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: 'False'
        volumes:
            - pgadmin:/root/.pgadmin
        ports:
            - "5050:80"